### ISSUE TITLE
Push master to gh-pages branch?

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/wet-boew-jekyll#43]
Once pull #42 is merged in, would it be possible to push the master branch's latest commits to the gh-pages branch?

Here's what wet-boew-jekyll's demo pages currently look like (walls of text due to outdated references to what became /v3.1-ci/):
http://wet-boew.github.io/wet-boew-jekyll/

Thanks :).

**Comment by pjackson28** [comment]
Done, the updates to gh-pages have been pushed.

**Comment by EricDunsworth** [comment]
@pjackson28 Thanks :).
