### ISSUE TITLE
GCWU Secondary menu examples overflow main content area

### ISSUE THREAD

**Issue by nschonni** [wet-boew/wet-boew-jekyll#5]
http://wet-boew.github.io/wet-boew-jekyll/theme-gcwu-fegc/cont-secnav1-en.html and
http://wet-boew.github.io/wet-boew-jekyll/theme-gcwu-fegc/cont-secnav2-en.html

See below for an example
![secondary nav overflow](https://f.cloud.github.com/assets/1297909/663745/ab64a826-d774-11e2-9021-887251d27a42.png)

Reproduced in Chrome and IE9

**Comment by pjackson28** [comment]
Fixed
