### ISSUE TITLE
Jekyll

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-jekyll#8]
I just saw your using jekyll this is awesome. Have you taken a look at prose.io?

**Comment by nschonni** [comment]
https://github.com/wet-boew/wet-boew-jekyll/blob/master/_config.yml#L25 :wink:

**Comment by sylus** [comment]
This is so cool I have been playing around with it myself for simple blog type sites where doesn't make sense for a CMS. I'll play around with this repo for sure :)

**Comment by thomasgohard** [comment]
@sylus I'm actually working on moving the WET documentation to use prose.io: https://github.com/wet-boew/wet-boew-documentation. I'm hoping to have the Wiki part of the documentation moved over in the next day or so as a first test of the system.
